services:
  flask:
    build:
      context: .         # folder proyek ini
      dockerfile: Dockerfile
    container_name: flask-app
    command: gunicorn app:app --bind 0.0.0.0:5000 --timeout 300 --workers 2
    ports:
      - "5000:5000"
      # Uncomment the following lines if you want to use GPU
    # environment:
    #   - CUDA_VISIBLE_DEVICES=0  # TANPA kutip ganda
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # runtime: nvidia
    env_file:
      - .env
    volumes:
      - huggingface-cache:/root/.cache/huggingface
      - torch-cache:/root/.cache/torch
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.1.32  # opsional, tambahkan versi agar tidak auto-update
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      # uncomment untuk GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

volumes:
  ollama-data:
  torch-cache:
  huggingface-cache: