services:
  flask:
    build:
      context: .         # folder proyek ini
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"       # Flask exposed by Gunicorn
    environment:
      - PYTORCH_FORCE_CPU=1
      - CUDA_VISIBLE_DEVICES=""
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama-data:
