services:
  flask:
    build:
      context: .         # folder proyek ini
      dockerfile: Dockerfile
    container_name: flask-app
    command: gunicorn app:app --bind 0.0.0.0:5000 --timeout 300 --workers 2
    ports:
      - "5000:5000"
    environment:
      - CUDA_VISIBLE_DEVICES=0  # TANPA kutip ganda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.9.5  # opsional, tambahkan versi agar tidak auto-update
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

volumes:
  ollama-data:
